# Generated by Django 5.2.8 on 2026-01-22 05:38

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="EssayTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Mavzu nomi")),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Tavsif (Matn ko'rinishida)"
                    ),
                ),
                (
                    "topic_file",
                    models.FileField(
                        blank=True,
                        help_text="Agar savol rasmda bo'lsa, shu yerga yuklang.",
                        null=True,
                        upload_to="topic_files/",
                        verbose_name="Savol Fayli (Rasm/PDF)",
                    ),
                ),
                ("deadline", models.DateTimeField(verbose_name="Topshirish muddati")),
                (
                    "submission_type",
                    models.CharField(
                        choices=[
                            ("text", "Faqat Matn"),
                            ("file", "Faqat Fayl/Rasm"),
                            ("both", "Ixtiyoriy (Matn yoki Fayl)"),
                        ],
                        default="both",
                        max_length=10,
                        verbose_name="Topshirish turi",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqt"
                    ),
                ),
            ],
            options={
                "verbose_name": "Yozma Ish Mavzusi",
                "verbose_name_plural": "✍️ Yozma Ish Mavzulari",
            },
        ),
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=50)),
                ("current", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Semestr",
                "verbose_name_plural": "Semestrlar",
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "Fan",
                "verbose_name_plural": "Fanlar",
            },
        ),
        migrations.CreateModel(
            name="Week",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_id", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=50)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
            options={
                "verbose_name": "Hafta",
                "verbose_name_plural": "Haftalar",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("student", "Talaba"),
                            ("teacher", "O'qituvchi"),
                            ("admin", "Admin"),
                        ],
                        default="student",
                        max_length=20,
                        verbose_name="Rol",
                    ),
                ),
                (
                    "hemis_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="Hemis ID",
                    ),
                ),
                (
                    "hemis_login",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Hemis Login"
                    ),
                ),
                (
                    "hemis_password",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Hemis Parol",
                    ),
                ),
                (
                    "hemis_token",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Token"
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="F.I.Sh"
                    ),
                ),
                (
                    "image",
                    models.URLField(blank=True, null=True, verbose_name="Rasm URL"),
                ),
                (
                    "group_name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Guruh"
                    ),
                ),
                (
                    "faculty",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Fakultet"
                    ),
                ),
                (
                    "specialty",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Mutaxassislik",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Kurs/Bosqich",
                    ),
                ),
                (
                    "gpa",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="GPA"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Telefon"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Manzil"
                    ),
                ),
                (
                    "birth_date",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Tug'ilgan sana",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Foydalanuvchi",
                "verbose_name_plural": "Foydalanuvchilar",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_id", models.CharField(max_length=20, null=True)),
                ("day_name", models.CharField(max_length=20)),
                ("lesson_time", models.CharField(max_length=50)),
                ("teacher", models.CharField(max_length=100, null=True)),
                ("room", models.CharField(max_length=50, null=True)),
                ("training_type", models.CharField(max_length=50, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.semester"
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.subject"
                    ),
                ),
            ],
            options={
                "verbose_name": "Dars Jadvali",
                "verbose_name_plural": "Dars Jadvallari",
                "ordering": ["week_id", "day_name", "lesson_time"],
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("hours", models.IntegerField()),
                ("type", models.CharField(max_length=20)),
                ("teacher", models.CharField(max_length=100, null=True)),
                ("training_type", models.CharField(max_length=50, null=True)),
                ("time_str", models.CharField(max_length=50, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.semester"
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.subject"
                    ),
                ),
            ],
            options={
                "verbose_name": "Davomat",
                "verbose_name_plural": "Davomatlar",
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, null=True, verbose_name="Javob matni"),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="essays/",
                        verbose_name="Yuklangan fayl (Rasm)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Tekshirilmoqda (AI)"),
                            ("ai_graded", "AI Baholadi"),
                            ("appeal", "Apellatsiya (Domlaga)"),
                            ("teacher_review", "Domla Tekshiruvida"),
                            ("done", "Baholandi"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Holat",
                    ),
                ),
                (
                    "ai_grade",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="AI Bahosi"
                    ),
                ),
                (
                    "ai_feedback",
                    models.TextField(blank=True, null=True, verbose_name="AI Izohi"),
                ),
                (
                    "teacher_grade",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="O'qituvchi Bahosi"
                    ),
                ),
                (
                    "teacher_feedback",
                    models.TextField(
                        blank=True, null=True, verbose_name="O'qituvchi Izohi"
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Topshirilgan vaqt"
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="core.essaytopic",
                        verbose_name="Mavzu",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Talaba",
                    ),
                ),
            ],
            options={
                "verbose_name": "Topshirilgan Ish",
                "verbose_name_plural": "📥 Topshirilgan Ishlar",
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("deadline", models.CharField(max_length=50)),
                ("status", models.CharField(max_length=50)),
                ("grade", models.CharField(default="-", max_length=10)),
                ("grade_val", models.FloatField(default=0)),
                ("max_ball", models.FloatField(default=0)),
                ("percentage", models.IntegerField(default=0)),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.semester"
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.subject"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Topshiriq/Baho",
                "verbose_name_plural": "Topshiriqlar va Baholar",
            },
        ),
    ]
