# Generated by Django 5.2.8 on 2026-01-22 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telegram_chat_id",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Telegram ID",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Tekshirilmoqda (AI)"),
                    ("ai_graded", "AI Baholadi (Qayta topshirish mumkin)"),
                    ("appeal", "Apellatsiya (Domlaga)"),
                    ("teacher_review", "Domla Tekshiruvida"),
                    ("done", "Baholandi"),
                    ("resubmit", "Qayta topshirishga ruxsat berildi"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Holat",
            ),
        ),
    ]
