# Generated by Django 5.2.8 on 2026-01-22 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_user_telegram_chat_id_alter_submission_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_key",
                    models.CharField(
                        max_length=255, verbose_name="Bildirishnoma Kaliti"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yuborilgan vaqt"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bot Tarixi",
                "verbose_name_plural": "🤖 Bot Bildirishnomalari",
                "unique_together": {("user", "notification_key")},
            },
        ),
    ]
