# Generated by Django 5.2.8 on 2026-01-22 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("listening", "🎧 Listening (Eshitish)"),
                            ("reading", "📖 Reading (O'qish)"),
                            ("writing", "✍️ Writing (Yozish)"),
                            ("speaking", "🗣️ Speaking (Gapirish)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(default="Section", max_length=100)),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="1=Listening, 2=Reading, 3=Writing, 4=Speaking",
                        verbose_name="Bosqich (1-4)",
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Vaqt (daqiqada)"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Faolmi?"),
                ),
                (
                    "audio_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="exam_audios/",
                        verbose_name="Audio Fayl",
                    ),
                ),
                (
                    "content_text",
                    models.TextField(
                        blank=True, null=True, verbose_name="Matn / Mavzu / Savol"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="exam_images/",
                        verbose_name="Rasm (Ixtiyoriy)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bo'lim",
                "verbose_name_plural": "Bo'limlar (Hovuz)",
                "ordering": ["section_type", "title"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("multi", "🔵 Test (A, B, C, D)"),
                            ("input", "📝 Yozma (So'z kiritish)"),
                        ],
                        default="multi",
                        max_length=10,
                        verbose_name="Savol Turi",
                    ),
                ),
                ("question_text", models.TextField(verbose_name="Savol matni")),
                (
                    "option_a",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Variant A"
                    ),
                ),
                (
                    "option_b",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Variant B"
                    ),
                ),
                (
                    "option_c",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Variant C"
                    ),
                ),
                (
                    "option_d",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Variant D"
                    ),
                ),
                (
                    "correct_option",
                    models.CharField(
                        blank=True,
                        choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                        max_length=1,
                        null=True,
                        verbose_name="To'g'ri Variant",
                    ),
                ),
                (
                    "correct_text",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="To'g'ri So'z",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=1)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="edu.section",
                    ),
                ),
            ],
            options={
                "verbose_name": "Savol",
                "verbose_name_plural": "Savollar",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ListeningSection",
            fields=[],
            options={
                "verbose_name": "🎧 Listening (Audio)",
                "verbose_name_plural": "1. Listening Bazasi",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("edu.section",),
        ),
        migrations.CreateModel(
            name="ReadingSection",
            fields=[],
            options={
                "verbose_name": "📖 Reading (Matn)",
                "verbose_name_plural": "2. Reading Bazasi",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("edu.section",),
        ),
        migrations.CreateModel(
            name="SpeakingSection",
            fields=[],
            options={
                "verbose_name": "🗣️ Speaking (Savol)",
                "verbose_name_plural": "4. Speaking Bazasi",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("edu.section",),
        ),
        migrations.CreateModel(
            name="WritingSection",
            fields=[],
            options={
                "verbose_name": "✍️ Writing (Mavzu)",
                "verbose_name_plural": "3. Writing Bazasi",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("edu.section",),
        ),
        migrations.CreateModel(
            name="StudentResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("is_completed", models.BooleanField(default=False)),
                ("overall_score", models.FloatField(default=0.0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Imtihon Natijasi",
                "verbose_name_plural": "5. Natijalar",
            },
        ),
        migrations.CreateModel(
            name="SectionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField(default=0.0)),
                ("user_answers", models.JSONField(blank=True, null=True)),
                ("correct_count", models.IntegerField(default=0)),
                ("written_essay", models.TextField(blank=True, null=True)),
                (
                    "audio_recording",
                    models.FileField(
                        blank=True, null=True, upload_to="student_speaking/"
                    ),
                ),
                (
                    "ai_feedback",
                    models.TextField(blank=True, null=True, verbose_name="AI Izohi"),
                ),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="edu.section"
                    ),
                ),
                (
                    "student_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_results",
                        to="edu.studentresult",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bo'lim Natijasi",
                "ordering": ["section__order"],
            },
        ),
    ]
