# Generated by Django 5.2.8 on 2026-01-22 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edu", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ListeningSection",
        ),
        migrations.DeleteModel(
            name="SpeakingSection",
        ),
        migrations.AlterModelOptions(
            name="readingsection",
            options={
                "verbose_name": "📖 Reading (Matn)",
                "verbose_name_plural": "1. Reading Bazasi",
            },
        ),
        migrations.AlterModelOptions(
            name="studentresult",
            options={
                "verbose_name": "Imtihon Natijasi",
                "verbose_name_plural": "3. Natijalar",
            },
        ),
        migrations.AlterModelOptions(
            name="writingsection",
            options={
                "verbose_name": "✍️ Writing (Mavzu)",
                "verbose_name_plural": "2. Writing Bazasi",
            },
        ),
        migrations.RemoveField(
            model_name="section",
            name="audio_file",
        ),
        migrations.RemoveField(
            model_name="sectionresult",
            name="audio_recording",
        ),
        migrations.AlterField(
            model_name="section",
            name="order",
            field=models.PositiveIntegerField(
                default=1,
                help_text="1=Reading, 2=Writing",
                verbose_name="Bosqich (1-2)",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="section_type",
            field=models.CharField(
                choices=[
                    ("reading", "📖 Reading (O'qish)"),
                    ("writing", "✍️ Writing (Yozish)"),
                ],
                max_length=20,
            ),
        ),
    ]
