# Generated by Django 5.2.8 on 2026-01-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edu", "0002_delete_listeningsection_delete_speakingsection_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sectionresult",
            name="written_essay",
        ),
        migrations.AddField(
            model_name="section",
            name="writing_task1_content",
            field=models.TextField(
                blank=True, null=True, verbose_name="Task 1: Savol Matni"
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="writing_task1_instruction",
            field=models.TextField(
                blank=True,
                help_text="Masalan: You should spend about 20 minutes on this task. Write at least 150 words.",
                null=True,
                verbose_name="Task 1: Yo'riqnoma",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="writing_task2_content",
            field=models.TextField(
                blank=True, null=True, verbose_name="Task 2: Savol Matni"
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="writing_task2_instruction",
            field=models.TextField(
                blank=True,
                help_text="Masalan: You should spend about 40 minutes on this task. Write at least 250 words.",
                null=True,
                verbose_name="Task 2: Yo'riqnoma",
            ),
        ),
        migrations.AddField(
            model_name="sectionresult",
            name="writing_task1_response",
            field=models.TextField(blank=True, null=True, verbose_name="Task 1 Javobi"),
        ),
        migrations.AddField(
            model_name="sectionresult",
            name="writing_task2_response",
            field=models.TextField(blank=True, null=True, verbose_name="Task 2 Javobi"),
        ),
        migrations.AlterField(
            model_name="section",
            name="content_text",
            field=models.TextField(
                blank=True, null=True, verbose_name="Reading: Matn (Passage)"
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="duration",
            field=models.PositiveIntegerField(
                default=60, verbose_name="Umumiy vaqt (daqiqada)"
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="exam_images/",
                verbose_name="Reading: Rasm",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="order",
            field=models.PositiveIntegerField(
                default=1, help_text="1=Reading, 2=Writing", verbose_name="Bosqich"
            ),
        ),
    ]
