# Generated by Django 5.2.8 on 2026-01-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edu", "0003_remove_sectionresult_written_essay_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="option_a",
        ),
        migrations.RemoveField(
            model_name="question",
            name="option_b",
        ),
        migrations.RemoveField(
            model_name="question",
            name="option_c",
        ),
        migrations.RemoveField(
            model_name="question",
            name="option_d",
        ),
        migrations.RemoveField(
            model_name="section",
            name="image",
        ),
        migrations.AlterField(
            model_name="question",
            name="correct_option",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TRUE", "TRUE"),
                    ("FALSE", "FALSE"),
                    ("NOT GIVEN", "NOT GIVEN"),
                ],
                max_length=20,
                null=True,
                verbose_name="To'g'ri Javob (TFNG)",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="correct_text",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="To'g'ri Javob (Gap Fill)",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("tfng", "⚪ True / False / Not Given"),
                    ("gap_fill", "📝 Gap Filling (So'z kiritish)"),
                ],
                default="tfng",
                max_length=10,
                verbose_name="Savol Turi",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="order",
            field=models.PositiveIntegerField(default=1, verbose_name="Bosqich"),
        ),
        migrations.AlterField(
            model_name="section",
            name="writing_task1_instruction",
            field=models.TextField(
                blank=True, null=True, verbose_name="Task 1: Yo'riqnoma"
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="writing_task2_instruction",
            field=models.TextField(
                blank=True, null=True, verbose_name="Task 2: Yo'riqnoma"
            ),
        ),
    ]
